"""add answers table

Revision ID: 07d117e06f77
Revises: 23b2da448c38
Create Date: 2026-09-29 00:14:37.444685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d117e06f77'
down_revision: Union[str, Sequence[str], None] = '23b2da448c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clarification_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hints_used >= 0', name='ck_answers_hints_non_negative'),
    sa.CheckConstraint('time_taken_seconds IS NULL OR time_taken_seconds >= 0', name='ck_answers_time_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    # ### end Alembic commands ###
