"""add questions table

Revision ID: 23b2da448c38
Revises: a7bad4a2d66c
Create Date: 2026-09-28 23:56:56.256719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b2da448c38'
down_revision: Union[str, Sequence[str], None] = 'a7bad4a2d66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('parent_question_id', sa.UUID(), nullable=True),
    sa.Column('follow_up_number', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('technical', 'aptitude', 'hr', name='round_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('source', sa.Enum('question_bank', 'llm_generated', name='question_source', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('difficulty', sa.Enum('fresher', 'senior', 'expert', name='question_difficulty', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(parent_question_id IS NULL) = (follow_up_number IS NULL)', name='ck_questions_parent_and_slot_consistent'),
    sa.CheckConstraint('follow_up_number BETWEEN 1 AND 3', name='ck_questions_follow_up_number_range'),
    sa.CheckConstraint('parent_question_id <> id', name='ck_questions_not_own_parent'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['parent_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'sequence_number', name='uq_questions_interview_sequence'),
    sa.UniqueConstraint('parent_question_id', 'follow_up_number', name='uq_questions_parent_follow_up_slot')
    )
    op.create_index(op.f('ix_questions_interview_id'), 'questions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_questions_parent_question_id'), 'questions', ['parent_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('interview_type'), 'interviews', "interview_type::text = ANY (ARRAY['resume_based'::character varying, 'role_based'::character varying]::text[])")
    op.create_check_constraint(op.f('interview_status'), 'interviews', "status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'abandoned'::character varying]::text[])")
    op.create_check_constraint(op.f('interview_mode'), 'interviews', "mode::text = ANY (ARRAY['practice'::character varying, 'strict'::character varying]::text[])")
    op.create_check_constraint(op.f('difficulty'), 'interviews', "difficulty::text = ANY (ARRAY['fresher'::character varying, 'senior'::character varying, 'expert'::character varying]::text[])")
    op.drop_index(op.f('ix_questions_parent_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_interview_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
