"""add video analyses table

Revision ID: 242206291b8e
Revises: 3a6c548160f8
Create Date: 2026-10-05 08:39:58.586900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242206291b8e'
down_revision: Union[str, Sequence[str], None] = '3a6c548160f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('face_visible_percentage', sa.Integer(), nullable=True),
    sa.Column('gaze_away_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('posture_issue_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('excessive_movement_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lighting_quality', sa.Enum('good', 'acceptable', 'poor', name='lighting_quality', native_enum=False, create_constraint=True, length=30), nullable=True),
    sa.Column('camera_positioning_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('excessive_movement_count >= 0', name='ck_video_analyses_movement_non_negative'),
    sa.CheckConstraint('face_visible_percentage IS NULL OR face_visible_percentage BETWEEN 0 AND 100', name='ck_video_analyses_face_visible_pct_range'),
    sa.CheckConstraint('gaze_away_count >= 0', name='ck_video_analyses_gaze_away_non_negative'),
    sa.CheckConstraint('posture_issue_count >= 0', name='ck_video_analyses_posture_non_negative'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_analyses')
    # ### end Alembic commands ###
