"""add communication analyses table

Revision ID: 3a6c548160f8
Revises: 3f4b951b48e5
Create Date: 2026-10-05 08:28:36.159522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6c548160f8'
down_revision: Union[str, Sequence[str], None] = '3f4b951b48e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('speaking_pace_wpm', sa.Integer(), nullable=True),
    sa.Column('filler_word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('long_pause_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_pause_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('average_volume_db', sa.Integer(), nullable=True),
    sa.Column('stt_confidence', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('filler_word_count >= 0', name='ck_comm_analyses_filler_non_negative'),
    sa.CheckConstraint('long_pause_count >= 0', name='ck_comm_analyses_long_pause_non_negative'),
    sa.CheckConstraint('stt_confidence IS NULL OR stt_confidence BETWEEN 0 AND 100', name='ck_comm_analyses_stt_confidence_range'),
    sa.CheckConstraint('total_pause_duration_seconds IS NULL OR total_pause_duration_seconds >= 0', name='ck_comm_analyses_pause_duration_non_negative'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_analyses')
    # ### end Alembic commands ###
