"""add interview evaluations table

Revision ID: 3f4b951b48e5
Revises: 8eed03f7c0e8
Create Date: 2026-10-05 08:10:36.363313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f4b951b48e5'
down_revision: Union[str, Sequence[str], None] = '8eed03f7c0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('topic_wise_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('video_score', sa.Integer(), nullable=True),
    sa.Column('improvement_notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('communication_score IS NULL OR communication_score BETWEEN 0 AND 100', name='ck_interview_evaluations_communication_score_range'),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100', name='ck_interview_evaluations_overall_score_range'),
    sa.CheckConstraint('video_score IS NULL OR video_score BETWEEN 0 AND 100', name='ck_interview_evaluations_video_score_range'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_evaluations')
    # ### end Alembic commands ###
