"""add interviews table

Revision ID: a7bad4a2d66c
Revises: c3218129011d
Create Date: 2026-09-28 23:39:40.518377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bad4a2d66c'
down_revision: Union[str, Sequence[str], None] = 'c3218129011d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('interview_type', sa.Enum('resume_based', 'role_based', name='interview_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.Enum('practice', 'strict', name='interview_mode', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('difficulty', sa.Enum('fresher', 'senior', 'expert', name='difficulty', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='interview_status', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_resume_id'), 'interviews', ['resume_id'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_resume_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
